= Documentation Toolchain


== Goals
Manage conversions between text written in ADOC and JSON representations of that content with DOCBOOK as an intermediary. 

Use ADOC or other DSL to write articles that are consistent with DOCBOOK standard.
 
* Convert ADOC to DOCBOOK
* Convert DOCBOOK to JSON
* Convert DOCBOOK to PDF
* Convert DOCBOOK.JSON to CMS.JSON



== Ideas

* Use gulp?
* Identify all libraries
* Use DOCBOOK as document database?
* Choose XML to JSON package: xml2js, xml-js, cheerio 

== Source Files

asciidoctor-writers-guide.adoc::
	ADOC copy of https://asciidoctor.org/docs/asciidoc-writers-guide/
howto.xml::
	This document is targeted at DocBook users who are considering switching from DocBook V4.x to DocBook V5.0. It describes differences between DocBook V4.x and V5.0 and provides some suggestions about how to edit and process DocBook V5.0 documents. There is also a section devoted to conversion of legacy documents from DocBook 4.x to DocBook V5.0. https://docbook.org/docs/howto/howto.xml

== References

=== cheerio 
- https://www.npmjs.com/package/cheerio

=== xml2js
- https://www.npmjs.com/package/xml2js

=== xml-js
- https://github.com/nashwaan/xml-js
- https://github.com/nashwaan/xml-js/issues/75
