= Documentation Toolchain


== Goals
Manage conversions between text written in ADOC and JSON representations of that content with DOCBOOK as an intermediary. 

Use ADOC or other DSL to write articles that are consistent with DOCBOOK standard.
 
* Convert ADOC to DOCBOOK
* Convert DOCBOOK to JSON
* Convert DOCBOOK to PDF
* Convert DOCBOOK.JSON to CMS.JSON



== Ideas

* Use gulp?
* Identify all libraries
* Use DOCBOOK as document database?
* Choose XML to JSON package: xml2js, xml-js, cheerio 

== Code

adoc2xml.js::
	Converts `asciidoctor-writers-guide.adoc` to DocBook using asciidoctor-docbook.js. See https://github.com/asciidoctor/asciidoctor-docbook.js/tree/master

docbook2json.js::
	Converts `howto.xml` to JSON using xml-js.

index.js::
	Converts `howto.xml` to JSON using xml2js.


== Source Files

asciidoctor-writers-guide.adoc::
	ADOC copy of https://asciidoctor.org/docs/asciidoc-writers-guide/
howto.xml::
	This document is targeted at DocBook users who are considering switching from DocBook V4.x to DocBook V5.0. It describes differences between DocBook V4.x and V5.0 and provides some suggestions about how to edit and process DocBook V5.0 documents. There is also a section devoted to conversion of legacy documents from DocBook 4.x to DocBook V5.0. https://docbook.org/docs/howto/howto.xml

== References

https://www.balisage.net/Accessibility/CFP.html[The Role of XML in Publishing Accessible Documents]::
	In this one-day symposium we will explore the role of XML in supporting accessibility. There is a moral as well as a legal imperative to make information and documents more accessible. What can we, the XML community, do to enable the creation and publication of accessible documents? What can we learn from the Accessibility community?
+
A substantial and growing portion of scientific, medical, legal, academic, engineering, and technical literature is now published and/or archived using XML as an intermediary format. XML is used in downstream processing of journal articles, books, laws, standards, and even newspapers without authors or readers being aware of it. That XML is critical to the richness and robustness of the publications received by the end user and the user experience. In a workflow where publishers create print, PDF, HTML, eBook, braille, tagged PDF, and WCAG-compliant HTML5 from the same XML source, information that is not in the XML cannot be made available to the reader/user/agent. As publishers strive to create more accessible documents, the XML embedded in the production process is key to the costs, and the success or failure, of the creation of accessible publications. Come explore ways to make our world more accessible using the XML tools we already possess. 


https://www.balisage.net/Proceedings/vol17/html/Walsh01/BalisageVol17-Walsh01.html[Marking up and marking down]::
	Markup provides a means of annotating a text such that its important characteristics are readily apparent. Simplicity of annotation and richness of meaning are often at odds. Through one lens, we can see the evolution of markup as developing along this fault line. TANSTAAFL. SGML provided mechanisms that reduced the complexity of annotation at considerable cost in implementation. XML reduced implementation cost at the expense of simplicity in annotation. HTML attempted to simplify annotation complexity and implementation cost by choosing a single tag set and inventing entirely new extension mechanisms. Online communities like GitHub and Stack Overflow have abandoned angle brackets in favor of Markdown, Common Mark, AsciiDoc, and other markup reminiscent of wiki syntax or SGML SHORTREF. 


http://wiki.open311.org/JSON_and_XML_Conversion/[XML to JSON Conventions]::
	Not everything in XML can be represented in JSON. The main reason for this is because XML allows inline metadata using tag attributes and there is no standard way of representing this metadata in JSON. Below you will find a reference point for an XML representation along with descriptions and JSON representations for each of these conventions.

https://github.com/asciidoctor/asciidoctor/wiki/Convert-Asciidoc-to-Docbook-for-use-with-Publican[Convert AsciiDoc to DocBook for use with Publican]::
	Publican expects certain structural rules to be followed in order to be able to build outputs with it. These expectations differ depending on whether you want to produce an article, book, or bookset. Booksets are pretty uncommon, so I won’t be testing them. This document will provide some notes about how to get from Asciidoc to Publican-built output for articles and books.


=== Stack Overflow

- https://stackoverflow.com/questions/20238493/xml2js-how-is-the-output

=== cheerio 
- https://www.npmjs.com/package/cheerio

=== xml2js
- https://www.npmjs.com/package/xml2js

=== xml-js
- https://github.com/nashwaan/xml-js
- https://github.com/nashwaan/xml-js/issues/75
